/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalWarrantyRouteImport } from './routes/portal.warranty'
import { Route as PortalSaltRouteImport } from './routes/portal.salt'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalChatRouteImport } from './routes/portal.chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWarrantyRoute = PortalWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSaltRoute = PortalSaltRouteImport.update({
  id: '/salt',
  path: '/salt',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalChatRoute = PortalChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PortalRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/portal/chat': typeof PortalChatRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/salt': typeof PortalSaltRoute
  '/portal/warranty': typeof PortalWarrantyRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/chat': typeof PortalChatRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/salt': typeof PortalSaltRoute
  '/portal/warranty': typeof PortalWarrantyRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/portal/chat': typeof PortalChatRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/salt': typeof PortalSaltRoute
  '/portal/warranty': typeof PortalWarrantyRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/api/chat'
    | '/portal/chat'
    | '/portal/documents'
    | '/portal/login'
    | '/portal/salt'
    | '/portal/warranty'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/portal/chat'
    | '/portal/documents'
    | '/portal/login'
    | '/portal/salt'
    | '/portal/warranty'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/api/chat'
    | '/portal/chat'
    | '/portal/documents'
    | '/portal/login'
    | '/portal/salt'
    | '/portal/warranty'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/warranty': {
      id: '/portal/warranty'
      path: '/warranty'
      fullPath: '/portal/warranty'
      preLoaderRoute: typeof PortalWarrantyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/salt': {
      id: '/portal/salt'
      path: '/salt'
      fullPath: '/portal/salt'
      preLoaderRoute: typeof PortalSaltRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/chat': {
      id: '/portal/chat'
      path: '/chat'
      fullPath: '/portal/chat'
      preLoaderRoute: typeof PortalChatRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalChatRoute: typeof PortalChatRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalSaltRoute: typeof PortalSaltRoute
  PortalWarrantyRoute: typeof PortalWarrantyRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalChatRoute: PortalChatRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalSaltRoute: PortalSaltRoute,
  PortalWarrantyRoute: PortalWarrantyRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
